// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9smxWnFzq9h8ZkVCLrh32bPQUCRFC3uE',
    appId: '1:989287356849:web:2835deed5109952a498590',
    messagingSenderId: '989287356849',
    projectId: 'uas-project-praktikum',
    authDomain: 'uas-project-praktikum.firebaseapp.com',
    storageBucket: 'uas-project-praktikum.appspot.com',
    measurementId: 'G-GHH1WH412N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGYOZucFMXqyESmYVHww3XOIQbldVE3M',
    appId: '1:989287356849:android:9e30c9b1e337f0a5498590',
    messagingSenderId: '989287356849',
    projectId: 'uas-project-praktikum',
    storageBucket: 'uas-project-praktikum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCwCROMNeFsheCHkRB7zsesTgOuwEUiI',
    appId: '1:989287356849:ios:fc4ff68157f0b6d6498590',
    messagingSenderId: '989287356849',
    projectId: 'uas-project-praktikum',
    storageBucket: 'uas-project-praktikum.appspot.com',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRCwCROMNeFsheCHkRB7zsesTgOuwEUiI',
    appId: '1:989287356849:ios:3d02883889e49751498590',
    messagingSenderId: '989287356849',
    projectId: 'uas-project-praktikum',
    storageBucket: 'uas-project-praktikum.appspot.com',
    iosBundleId: 'com.example.uas.RunnerTests',
  );
}
